export const SET_PIZZA_SIZE = "SET_PIZZA_SIZE";
export const SET_PIZZA_CRUST = "SET_PIZZA_CRUST";
export const ADD_PIZZA_TOPPING = "ADD_PIZZA_TOPPINGS";
export const REMOVE_PIZZA_TOPPING = "REMOVE_PIZZA_TOPPING";
export const UPDATE_PIZZA_TOPPING = "UPDATE_PIZZA_TOPPING";
